configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZmQwNjc3YmI2NmRlNDMxNWQ5NjJlMjY5NzU5YmU5YjYyNjkwOGI4ZDU5MTY5YjMxMWIwNTA2OGFlZGM3ZWRmYjY3OWYxOGY1ZjRmYjM5NjY0ZGRjYWU0Y2E2NjI5OTZkNjdkYzYwMWU0ZGZjM2ZmMmU2YWVjMGE3NDQ2ODcxNTM=
