spring:
  cloud:
    function:
      definition: kafkaConsumer;kafkaProducer
    stream:
      kafka:
        binder:
          replicationFactor: 1
          auto-create-topics: false
          brokers: localhost:9092
      bindings:
        binding-out-0:
          content-type: text/plain
          group: order
        kafkaConsumer-in-0:
          destination: sse-topic
          content-type: text/plain
          group: order
        kafkaProducer-out-0:
          content-type: text/plain
          group: order
